apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todo-app-mongo.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.volume.capacity }}
  storageClassName: ""
  volumeName: {{ include "todo-app-mongo.fullname" . }}-pv
