apiVersion: v1
kind: Service
metadata:
  labels:
  {{- include "todo-app-mongo.labels" . | nindent 4 }}
  name: {{ include "todo-app-mongo.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
  {{- include "todo-app-mongo.selectorLabels" . | nindent 4 }}
