apiVersion: v1
kind: Pod
metadata:
  name: {{ include "todo-app-mongo.fullname" . }}
  labels:
  {{- include "todo-app-mongo.labels" . | nindent 4 }}
spec:
  volumes:
    - name: {{ include "todo-app-mongo.fullname" . }}-vol
      persistentVolumeClaim:
        claimName: {{ include "todo-app-mongo.fullname" . }}-pvc
  containers:
    - image: mongo
      name: mongo-container
      command:
        - mongod
        - "--bind_ip"
        - "0.0.0.0"
      ports:
        - containerPort: {{ .Values.service.port }}
      volumeMounts:
        - name: {{ include "todo-app-mongo.fullname" . }}-vol
          mountPath: {{ .Values.volume.mountPath }}