apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "todo-app-mongo.fullname" . }}-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{.Values.volume.capacity}}
  hostPath:
    path: {{ .Values.volume.hostPath }}
